config:
  # Defines the consul DNS name for the metrics API that allows connection via
  # the CollectD protocol
  - key: config/services/metrics/protocols/collectd/host
    value: collectd.metrics

  # Defines the port for the metrics API that allows connection via
  # the CollectD protocol
  - key: config/services/metrics/protocols/collectd/port
    value: 25826

  # Defines the consul DNS name for the metrics API that allows connection via
  # the Graphite protocol
  - key: config/services/metrics/protocols/graphite/host
    value: graphite.metrics

  # Defines the port for the metrics API that allows connection via
  # the Graphite protocol
  - key: config/services/metrics/protocols/graphite/port
    value: 2003

  # Defines the consul DNS name for the metrics API that allows connection via
  # a HTTP protocol
  - key: config/services/metrics/protocols/http/host
    value: http.metrics

  # Defines the port for the metrics API that allows connection via
  # a HTTP protocol
  - key: config/services/metrics/protocols/http/port
    value: 8086

  # Defines the consul DNS name for the metrics API that allows connection via
  # the OpenTSDB protocol
  - key: config/services/metrics/protocols/opentsdb/host
    value: opentsdb.metrics

  # Defines the port for the metrics API that allows connection via
  # the OpenTSDB protocol
  - key: config/services/metrics/protocols/opentsdb/port
    value: 4242

  # Defines the consul DNS name for the metrics API that allows connection via
  # an UDP protocol
  - key: config/services/metrics/protocols/udp/host
    value: udp.metrics

  # Defines the port for the metrics API that allows connection via
  # an UDP protocol
  - key: config/services/metrics/protocols/udp/port
    value: 8089
