{
 "title": "InfluxDB",
 "tags": [
  "service",
  "consul.metrics",
  "meta"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "_bucket", "label": "Bucket", "query": "10m,30m,1h,6h,12h,1d,7d" },
   { "name": "_host", "label": "Host", "query": "nzdimetric10-01" }
  ]
 },
 "panels": [
  {
   "title": "InfluxDB size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "shard",
     "query": "SELECT sum(\"diskBytes\") FROM \"shard\" WHERE \"database\" = 'opentsdb' AND \"hostname\" = 'VDT155' AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "NZDIMETRIC10-01" }
     ]
    }
   ]
  },
  {
   "title": "Points Written",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No.  Measurements",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    }
   ]
  },
  {
   "title": "No. Series",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "DB size",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "shard",
     "query": "SELECT sum(\"diskBytes\") FROM \"shard\" WHERE \"database\" = 'opentsdb' AND \"hostname\" = 'VDT155' AND $timeFilter GROUP BY time(15s) fill(0)",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    },
    {
     "alias": "Cache (disk)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tsm1_wal",
     "query": "SELECT sum(\"diskBytes\") FROM \"shard\" WHERE \"database\" = 'opentsdb' AND \"hostname\" = 'VDT155' AND $timeFilter GROUP BY time(15s) fill(0)",
     "select": [
      [
       { "params": [ "currentSegmentDiskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    },
    {
     "alias": "Cache (mem)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tsm1_cache",
     "query": "SELECT sum(\"diskBytes\") FROM \"shard\" WHERE \"database\" = 'opentsdb' AND \"hostname\" = 'VDT155' AND $timeFilter GROUP BY time(15s) fill(0)",
     "select": [
      [
       { "params": [ "memBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    },
    {
     "alias": "Cache",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tsm1_cache",
     "query": "SELECT sum(\"diskBytes\") FROM \"shard\" WHERE \"database\" = 'opentsdb' AND \"hostname\" = 'VDT155' AND $timeFilter GROUP BY time(15s) fill(0)",
     "select": [
      [
       { "params": [ "cachedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    }
   ]
  },
  {
   "title": "Total datapoints",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Shard: $tag_id",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shard",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "database", "operator": "=", "value": "opentsdb" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Queries",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Client Error",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Server Error",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurements/Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Series",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Measurements",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenOK" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory/Cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win.cpu.load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Mem",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os.mem.percent_free",
     "query": "SELECT 100 - mean(\"value\") FROM \"os.mem.percent_free\" WHERE \"host\" =~ /^$_host$/ AND $timeFilter GROUP BY time($_bucket) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$_host$/" }
     ]
    },
    {
     "alias": "Influx",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "Sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}